// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-h-ApOagfRClWG-6B9iawQOPz5uQTaSU',
    appId: '1:38391014680:web:a129d5e91439b5c8d8aa6d',
    messagingSenderId: '38391014680',
    projectId: 'alma-diario',
    authDomain: 'alma-diario.firebaseapp.com',
    storageBucket: 'alma-diario.firebasestorage.app',
    measurementId: 'G-43D2J6WZKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSraorj5srtYCqlQfiieOySF9v9X6bcRU',
    appId: '1:38391014680:android:eb1a09678882052cd8aa6d',
    messagingSenderId: '38391014680',
    projectId: 'alma-diario',
    storageBucket: 'alma-diario.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3yQOELiIrGGGryQtgr2hL95dg0C5zmeI',
    appId: '1:38391014680:ios:6ddc6c591fe3dc52d8aa6d',
    messagingSenderId: '38391014680',
    projectId: 'alma-diario',
    storageBucket: 'alma-diario.firebasestorage.app',
    iosClientId: '38391014680-ouet52arbij4o58p8gdaut8beulasfun.apps.googleusercontent.com',
    iosBundleId: 'com.example.almaDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3yQOELiIrGGGryQtgr2hL95dg0C5zmeI',
    appId: '1:38391014680:ios:6ddc6c591fe3dc52d8aa6d',
    messagingSenderId: '38391014680',
    projectId: 'alma-diario',
    storageBucket: 'alma-diario.firebasestorage.app',
    iosClientId: '38391014680-ouet52arbij4o58p8gdaut8beulasfun.apps.googleusercontent.com',
    iosBundleId: 'com.example.almaDiary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-h-ApOagfRClWG-6B9iawQOPz5uQTaSU',
    appId: '1:38391014680:web:d73d558946032362d8aa6d',
    messagingSenderId: '38391014680',
    projectId: 'alma-diario',
    authDomain: 'alma-diario.firebaseapp.com',
    storageBucket: 'alma-diario.firebasestorage.app',
    measurementId: 'G-NX1PWRXM7X',
  );
}
